{% set version = "23.0.0" %}

package:
  name: gunicorn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gunicorn/gunicorn-{{ version }}.tar.gz
  sha256: f014447a0101dc57e294f6c18ca6b40227a4c90e9bdb586042628030cba004ec

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  preserve_egg_dir: true
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - setuptools >=3.0
    - packaging
    - portalocker

test:
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers
  commands:
    - gunicorn --help
  requires:
    - python
    - paste
    - pastedeploy

about:
  home: http://gunicorn.org
  license: MIT
  license_file: LICENSE
  summary: WSGI HTTP Server for UNIX

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jakirkham
    - sodre
