{% set version = "25.1.0" %}

package:
  name: gunicorn
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gunicorn/gunicorn-{{ version }}.tar.gz
  sha256: 1426611d959fa77e7de89f8c0f32eed6aa03ee735f98c01efba3e281b1c47616

build:
  skip: true  # [win]
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  preserve_egg_dir: true
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools >=3.0
    - packaging

test:
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers
  commands:
    - gunicorn --help
  requires:
    - paste
    - pastedeploy

about:
  home: http://gunicorn.org
  license: MIT
  license_file: LICENSE
  summary: WSGI HTTP Server for UNIX

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jakirkham
    - sodre
