{% set version = "20.0.1" %}

package:
  name: gunicorn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gunicorn/gunicorn-{{ version }}.tar.gz
  sha256: af142bd7f6d176872e18681c847b9c0e79bc98ac24b91f95da04b18a6a77f282

build:
  skip: True  # [win]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  preserve_egg_dir: True
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run
    - gunicorn_paster=gunicorn.app.pasterapp:run

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers
  commands:
    - gunicorn --help
    - gunicorn_paster --help
  requires:
    - paste
    - pastedeploy

about:
  home: http://gunicorn.org
  license: MIT
  license_file: LICENSE
  summary: 'WSGI HTTP Server for UNIX'

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jakirkham
    - sodre
