{% set version = "19.8.0" %}

package:
  name: gunicorn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gunicorn/gunicorn-{{ version }}.tar.gz
  sha256: eb8d8924b117a609fae9f8cd85df0cad3535dd613fdbcdbba3ee88d5459f1d4f

build:
  skip: True  # [win]
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  preserve_egg_dir: True
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run
    - gunicorn_paster=gunicorn.app.pasterapp:run

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  requires:
    - paste
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers
  commands:
    - gunicorn --help
    - gunicorn_paster --help

about:
  home: http://gunicorn.org
  license: MIT
  license_file: LICENSE
  summary: 'WSGI HTTP Server for UNIX'

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jakirkham
    - sodre
